export const API_VERSION: string = "/api/v1";

export enum Role {
  SUPER_ADMIN = "SuperAdmin",
  ADMIN = "Admin",
  FRONTEND = "Frontend",
  BACKEND = "Backend",
  PRODUCT_MANAGER = "ProductManagers",
  PRODUCT_DESIGNER = "ProductDesigners",
  SELLER = "Seller",
  BUYER = "Buyer",
}

export const ROLES_FETCHED_SUCCESSFUL = "ALL ROlES GOTTEN SUCCESSFUL";
export const ROLE_CREATED = "ROLE CREATED";
export const SOCIALS_CREATED = "SOCIALS CREATED";
export const SOCIALS_FETCHED_SUCCESSFUL = "ALL SOCIALS GOTTEN SUCCESSFUL";
export const SIGN_UP_INITIATED = "SIGN UP INITIATED";
export const SOCIAL_SIGN_UP_COMPLETED = " SOCIAL SIGN UP COMPLETED";
export const EMAIL_SIGN_UP_COMPLETED = " EMAIL SIGN UP COMPLETED";
export const EMAIL_SIGN_UP_INITIATED = " EMAIL SIGN UP INITIATED";
export const RESEND_VERIFICATION = "VERIFICATION RESENT ";
export const SEND_VERIFICATION = "VERIFICATION SENT ";
export const PROFILE_COMPLETED = "PROFILE COMPLETED";
export const EMAIL_AVAILAIBLE="EMAIL AVAILABLE"
export const User_NAME_AVAILAIBLE="USER NAME AVAILABLE"
export const LOGIN_SUCCESSFUL ="LOGIN SUCCESSFUL"
export const LOGOUT_SUCCESSFUL ="LOGOUT SUCCESSFUL"
export const PROFILE_FETCHED_SUCCESSFUL ="PROFILE FETCHED SUCCESSFUL"
export const PROFILE_UPDATED_SUCCESSFUL ="PROFILE UPDATED SUCCESSFUL"
export const CHANGE_PASSWORD = "PASSWORD CHANGED SUCCESSFUL"
export const GET_AUTH = "AUTH METHODS FETCHED"
export const LINK_AUTH = "AUTH METHODS LINKED"
export const UN_LINK_AUTH = "AUTH METHODS UNLINKED"
export const FORGOT_PASSWORD = "PASSWORD RESET INSTRUCTIONS SENT"
export const RESET_PASSWORD = "PASSWORD RESET SUCCESSFUL, YOU CAN NOW LOGIN WITH YOUR NEW PASSWORD"



export enum SocialSignIns {
  EMAIL = "email",
  GOOGLE = "google",
  FACEBOOK = "facebook",
  GITHUB = "github",
  LINKEDIN = "linkedin",
  TWITTER = "twitter",
}
